module.exports = {
	extends: ['@antfu', 'turbo', 'prettier'],
	rules: {
		'n/prefer-global/process': 'off',
		'antfu/top-level-function': 'off',
		'sort-imports': 'off',
		'vue/attributes-order': 'off',
		'vue/component-tags-order': 'off',
		'vue/attribute-hyphenation': 'off',
		'vue/v-on-event-hyphenation': 'off',
		'vue/define-macros-order': 'off',
		'@typescript-eslint/consistent-type-definitions': ['error', 'type'],
	},

	// Ignore autogenerated folder
	ignorePatterns: ['packages/database/src/zod/**.ts'],
}
